version: "3.8"

services:
  api:
    container_name: storeapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - MPassSamlOptions__ServiceRootUrl=http://localhost:8080
      - ASPNETCORE_URLS=http://*:8080/
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=db;database=StoreAPI;User=sa;Password=Your_password123;

    ports:
      - 8080:8080

    depends_on:
      - db

  db:
    container_name: store-mssql-server
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
